version: "3.9"

services:
  auth-be:
    container_name: auth-be
    image: auth-be:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8060:8060"
    restart: unless-stopped

volumes:
  postgres_data:
